import type { Metadata } from "next";
import { Inter, Lobster } from "next/font/google";
import { AblyProvider } from "./contexts/AblyContext";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const lobster = Lobster({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lobster",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lobster.variable}>
      <body className={inter.className}>
        <AblyProvider>{children}</AblyProvider>
      </body>
    </html>
  );
}
